/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShutdownRouteImport } from './routes/shutdown'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as JobsJobIdReviewRouteImport } from './routes/jobs.$jobId.review'

const ShutdownRoute = ShutdownRouteImport.update({
  id: '/shutdown',
  path: '/shutdown',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdReviewRoute = JobsJobIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => JobsJobIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/shutdown': typeof ShutdownRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/jobs/$jobId/review': typeof JobsJobIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/shutdown': typeof ShutdownRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/jobs/$jobId/review': typeof JobsJobIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/shutdown': typeof ShutdownRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/jobs/$jobId/review': typeof JobsJobIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/dashboard'
    | '/diagnostics'
    | '/login'
    | '/shutdown'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/$jobId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config'
    | '/dashboard'
    | '/diagnostics'
    | '/login'
    | '/shutdown'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/$jobId/review'
  id:
    | '__root__'
    | '/'
    | '/config'
    | '/dashboard'
    | '/diagnostics'
    | '/login'
    | '/shutdown'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/$jobId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  LoginRoute: typeof LoginRoute
  ShutdownRoute: typeof ShutdownRoute
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
  JobsNewRoute: typeof JobsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shutdown': {
      id: '/shutdown'
      path: '/shutdown'
      fullPath: '/shutdown'
      preLoaderRoute: typeof ShutdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/review': {
      id: '/jobs/$jobId/review'
      path: '/review'
      fullPath: '/jobs/$jobId/review'
      preLoaderRoute: typeof JobsJobIdReviewRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
  }
}

interface JobsJobIdRouteChildren {
  JobsJobIdReviewRoute: typeof JobsJobIdReviewRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdReviewRoute: JobsJobIdReviewRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRoute,
  DashboardRoute: DashboardRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  LoginRoute: LoginRoute,
  ShutdownRoute: ShutdownRoute,
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
  JobsNewRoute: JobsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
